const express = require("express")
const cors = require("cors")
const {user} = require("./routes/user")
const {laundry} = require("./routes/laundry")
const app = express()
const mongoose = require("mongoose")
const {auth} = require("./controllers/auth")
require("dotenv").config()
app.use(cors())
mongoose.connect("mongodb://localhost:27017/laundry")
const PORT = process.env.PORT
app.use(express.json())
app.use(express.urlencoded({extended: true}))
app.use(auth)
app.use("/user", user)
app.use("/laundry", laundry)
app.listen(PORT, () => {
    console.log(`server started on ${PORT}`)
})